services:
  marketplace-db:
    image: mariadb:10.6
    container_name: marketplace-db
    env_file:
      - .env
    ports:
      - "3306:3306"
    networks:
      - marketplace-network
    volumes:
      - db_data:/var/lib/mysql
      - ./marketplace-schema.sql:/docker-entrypoint-initdb.d/marketplace.sql

  marketplace-backend:
    build:
      context: ../marketplace-backend
      dockerfile: ../docker/Dockerfile.backend
    container_name: marketplace-backend
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - marketplace-db
    networks:
      - marketplace-network

  marketplace-frontend:
    build:
      context: ../marketplace-frontend
      dockerfile: ../docker/Dockerfile.frontend
    container_name: marketplace-frontend
    env_file:
      - .env
    ports:
      - "4200:80"
    depends_on:
      - marketplace-backend
    networks:
      - marketplace-network

networks:
  marketplace-network:
    driver: bridge

volumes:
  db_data:

